services:
  # Nginx service
  web:
    build:
      dockerfile: ./nginx/Dockerfile
    ports:
      - '8080:80'
    volumes:
      - ./nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf

  # PHP service
  app:
    build:
      dockerfile: ./php/Dockerfile
      target: app

  # MySQL service
  db:
    image: mysql:9.1.0
    volumes:
      - mysqldata:/var/lib/mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: docker-php
      MYSQL_USER: user
      MYSQL_PASSWORD: secret

volumes:
  # docker volume for MySQL data persistence
  mysqldata:
